language: php
php:
  - 5.3
  - 5.4
before_script:
  - sudo apt-get install xvfb
  - sudo /usr/bin/Xvfb :0 -screen 0 1024x768x24 -fbdir /var/run -ac &
  - wget https://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2 -O /tmp/wkhtmltopdf.tar.bz2
  - sudo tar -xvf /tmp/wkhtmltopdf.tar.bz2 -C /usr/local/bin/
  - sudo mv /usr/local/bin/wkhtmltopdf-amd64 /usr/local/bin/wkhtmltopdf
  - uname -a
  - ldd /usr/local/bin/wkhtmltopdf
  - mysql -e 'create database fwdays_com_testing;'
  - curl -s https://getcomposer.org/installer | php -- --quiet
  - php composer.phar install
  - app/console --env=test doctrine:schema:create
script:
  - phpunit -c app/
  - bin/run-all-features
notifications:
  email:
      - stepan.tanasiychuk@gmail.com
