imports:
    - { resource: parameters.ini }
    - { resource: services.yml }
    - { resource: security.yml }
    - { resource: multi_lang.yml }
    - { resource: mobile_detect.yml }

parameters:
    graylog.fromname: "https://frameworksdays.com"
    rss.title: "Frameworks Days"
    rss.description: "Новости событий, которые проходят под эгидой Frameworks Days"
    google_apikey: "%google_api_key%"

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions/"


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:colorpicker.html.twig'
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
    globals:
        google_apikey: "%google_api_key%"
        ga_tracking_id: "%tracking_id%"
        google_site_key: "%google_captcha_site_key%"
        facebook_api_id: "%facebook_client_id%"
#    form:
#        resources: ['form_table_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
    workers:
        cache_busting: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# DoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            loggable: false
            sluggable: false
            timestampable: true
            translatable: true
            tree: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"

# KnpMenuBundle
knp_menu:
    twig: true

#avalanche_imagine:
#    cache_prefix: /tmp/media/cache
#    filters:
#        speaker_thumb:
#            type:    thumbnail
#            options: { size: [64, 64], mode: outbound }
#        speaker_size:
#            source_root: "%kernel.root_dir%/../web/uploads/speakers"
#            type:    crop
#            options: { start: [0, 0], size: [232, 232]}

liip_imagine:
    filter_sets:
        cache: ~
        speaker_size:
            filters:
                relative_resize: { widen: 232 }
                crop: { size: [ 232, 232 ], start: [ 0, 0 ] }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Application\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: application_user_registration
        confirmation:
            enabled:    false
            template:   FOSUserBundle:Registration:email.txt.twig
    profile:
        form:
            type: application_user_profile
            handler: application_user.profile.form.handler
    from_email:
        address:        orgs@fwdays.com
        sender_name:    "Frameworks Days"
    service:
        user_manager: stfalcon.user_manager

stfalcon_event:
    interkassa:
        shop_id: "%interkassa_shop_id%"
        secret: "%interkassa_secret%"
    discount: 0.2

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
        sonata.block.service.statistic: ~

sonata_admin:
    title: framework days
    templates:
        layout: "::admin.html.twig"
        user_block: '::user_block.html.twig'
    dashboard:
        blocks:
            # display two dashboard blocks
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups:
                      - "Пользователи"
                      - "События"
                      - "Новости"
                      - "Статистика"
                      - "group.translation"
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Спонсоры", "Билеты", "Страницы", "Рассылки"]
            -
                position: left
                type: sonata.block.service.statistic


services:
     gelf.publisher:
         class: Application\Bundle\DefaultBundle\Publisher\MessagePublisher
         arguments: [%graylog.fromname%, %graylog.hostname%, %graylog.port%]
     monolog.gelf_handler:
         class: Monolog\Handler\GelfHandler
         arguments: [@gelf.publisher]
     monolog.processor.added_host:
             class: Monolog\Processor\WebProcessor
             tags:
                 - { name: monolog.processor, method: __invoke }

vich_uploader:
     db_driver: orm
     mappings:
          sponsor_image:
              uri_prefix: /uploads/sponsors
              upload_destination: %kernel.root_dir%/../web/uploads/sponsors
          speaker_photo:
              uri_prefix: /uploads/speakers
              upload_destination: %kernel.root_dir%/../web/uploads/speakers
              #all images in upload folder could be deleted
              delete_on_update: true
          event_image:
              uri_prefix: /uploads/events
              upload_destination: %kernel.root_dir%/../web/uploads/events

ornicar_gravatar: ~

accord_mandrill_swift_mailer:
    api_key: %mandrill_api_key%

hwi_oauth:
    firewall_names: [main]
    connect:
        account_connector: app.provider.oauth
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "%facebook_client_id%"
            client_secret:       "%facebook_client_secret%"
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,first_name,last_name"
            paths:
                email: email
            options:
                display: page
        google:
            type:                google
            client_id:           "%google_client_id%"
            client_secret:       "%google_client_secret%"
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email