imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   fwdays_com_testing

liip_functional_test: ~
#doctrine:
#    dbal:
#        driver:   pdo_sqlite
#        path:     %kernel.cache_dir%/test.db

vich_uploader:
     db_driver: orm
     mappings:
          sponsor_image:
              uri_prefix: /tmp/uploads/sponsors
              upload_destination: %kernel.root_dir%/../web/tmp/uploads/sponsors
          speaker_photo:
              uri_prefix: /tmp/uploads/speakers
              upload_destination: %kernel.root_dir%/../web/tmp/uploads/speakers
          event_image:
              uri_prefix: /tmp/uploads/events
              upload_destination: %kernel.root_dir%/../web/tmp/uploads/events

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:
            margin-bottom: 0
            margin-left:   0
            margin-right:  0
            margin-top:    0
            page-size:     A5
            orientation:   Landscape
            use-xserver:   true
