imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
#        result_cache_driver:
#            type: memcache
#            host: localhost
#            port: 11211

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_main
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        sentry:
            type:  raven
            dsn: "http://ee926678a4cb4ea39b11c07a043d874a:53f5e4cf3c2f4fa69021f99bdebefa7c@sentry.stfalcon.com/48"
            level: error
#        gelf:
#           type: service
#           id: monolog.gelf_handler
#           level: error
        grouped_main:
            type:    group
            members: [nested, sentry]
#parameters:
#     graylog.hostname: 10.0.0.1
#     graylog.port: 12201 #стандартный порт
#     graylog.fromname: "https://frameworksdays.com"