imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
#        result_cache_driver:
#            type: memcache
#            host: localhost
#            port: 11211
sentry:
    skip_capture:
        - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
    dsn: "%sentry_dsn_prod%"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped_main
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
#        sentry:
#            type:  raven
#            level: error
        grouped_main:
            type:    group
            members: [nested]
#parameters:
#     graylog.hostname: 10.0.0.1
#     graylog.port: 12201 #стандартный порт
#     graylog.fromname: "https://frameworksdays.com"