imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
#    form:
#        resources: ['form_table_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# DoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            loggable: false
            sluggable: false
            timestampable: true
            translatable: false
            tree: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#    spool:     { type: memory }

# KnpMenuBundle
knp_menu:
    twig: true

avalanche_imagine:
    cache_prefix: /tmp/media/cache
    filters:
        speaker_thumb:
            type:    thumbnail
            options: { size: [64, 64], mode: outbound }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Application\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: application_user_registration
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Registration:email.txt.twig
    profile:
        form:
            type: application_user_profile
            handler: application_user.profile.form.handler
    from_email:
        address:        orgs@fwdays.com
        sender_name:    "Frameworks Days"

stfalcon_payment:
    interkassa:
        shop_id: "24C1AF18-3D1A-44FC-9C32-210336A4B231"
        secret: %interkassa_secret%
    discount: 0.2

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

sonata_admin:
    templates:
        layout: "::admin.html.twig"

services:
     gelf.publisher:
         class: Gelf\MessagePublisher
         arguments: [%graylog.hostname%, %graylog.port%]
     monolog.gelf_handler:
         class: Monolog\Handler\GelfHandler
         arguments: [@gelf.publisher]
     monolog.processor.added_host:
             class: Monolog\Processor\WebProcessor
             tags:
                 - { name: monolog.processor, method: __invoke }

vich_uploader:
     db_driver: orm
     mappings:
          sponsor_image:
              uri_prefix: /uploads/sponsors
              upload_destination: %kernel.root_dir%/../web/uploads/sponsors
          speaker_photo:
              uri_prefix: /uploads/speakers
              upload_destination: %kernel.root_dir%/../web/uploads/speakers
              #all images in upload folder could be deleted
              delete_on_update: true
          event_image:
              uri_prefix: /uploads/events
              upload_destination: %kernel.root_dir%/../web/uploads/events

ornicar_gravatar: ~
