imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: ru }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:   %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
#    form:
#        resources: ['form_table_layout.html.twig']

# Assetic Configuration
assetic:
#    debug:          %kernel.debug%
    use_controller: false
    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# DoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            loggable: false
            sluggable: false
            timestampable: true
            translatable: false
            tree: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

# KnpMenuBundle
knp_menu:
    twig: true

avalanche_imagine:
    cache_prefix: /tmp/media/cache
    filters:
        speaker_thumb:
            type:    thumbnail
            options: { size: [64, 64], mode: outbound }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Application\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: application_user_registration
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Registration:email.txt.twig
    profile:
        form:
            type: application_user_profile
            handler: application_user.profile.form.handler
    from_email:
        address:        orgs@fwdays.com
        sender_name:    "Frameworks Days"

stfalcon_payment:
    interkassa:
        shop_id: "24C1AF18-3D1A-44FC-9B32-210336A4B231"
        secret: %interkassa_secret%

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
