imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
#        result_cache_driver:
#            type: memcache
#            host: localhost
#            port: 11211

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        gelf:
           type: service
           id: monolog.gelf_handler
           level: debug

parameters:
     graylog.hostname: 10.0.0.1
     graylog.port: 12201 #стандартный порт