#StfalconEventBundle:
#    resource: "@StfalconEventBundle/Controller/"
#    type:     annotation
#    prefix:   /

ApplicationDefaultBundle:
    resource: "@ApplicationDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

#StfalconSponsorBundle:
#    resource: "@StfalconSponsorBundle/Controller/"
#    type:     annotation
#    prefix:   /

#ApplicationUserBundle:
#    resource: "@ApplicationDefaultBundle/Controller/"
#    type:     annotation
#    prefix:   /

#app_backend:
#    resource: "@StfalconEventBundle/Controller/Admin"
#    type:     annotation
#    prefix:   /admin
#    options:
#        i18n: false

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    options:
        i18n: false

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    options:
        i18n: false

sonata_admin_ticket_check:
    pattern:  /admin/ticket/check
    defaults: { _controller: ApplicationDefaultBundle:TicketAdmin:check }
    options:
        i18n: false

admin_show_statistic:
    pattern:  /admin/statistic
    defaults: { _controller: ApplicationDefaultBundle:Admin:showStatistic }
    options:
        i18n: false

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type: imagine
    options:
        i18n: false

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        i18n: false

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    options:
        i18n: false


hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    options:
        i18n: false

facebook_login:
    path: /login/check-facebook
    options:
        i18n: false

google_login:
    path: /login/check-google
    options:
        i18n: false