StfalconPaymentBundle:
    resource: "@StfalconPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

StfalconEventBundle:
    resource: "@StfalconEventBundle/Controller/"
    type:     annotation
    prefix:   /

StfalconNewsBundle:
    resource: "@StfalconNewsBundle/Controller/"
    type:     annotation
    prefix:   /

StfalconPageBundle:
    resource: "@StfalconPageBundle/Controller/"
    type:     annotation
    prefix:   /page

ApplicationDefaultBundle:
    resource: "@ApplicationDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

StfalconSponsorBundle:
    resource: "@StfalconSponsorBundle/Controller/"
    type:     annotation
    prefix:   /

#ApplicationUserBundle:
#    resource: "@ApplicationDefaultBundle/Controller/"
#    type:     annotation
#    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type: imagine

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
